### ISSUE TITLE
not working for zip format

### ISSUE THREAD

**Issue by simminni** [mitsuhiko/unp#6]
extracting a zip format file resulting in error:

Unpacking "/home/shiva/Desktop/abc.zip" with unzip
Traceback (most recent call last):
  File "/usr/local/bin/unp", line 9, in <module>
    load_entry_point('unp==0.2', 'console_scripts', 'unp')()
  File "/usr/local/lib/python3.4/dist-packages/click-3.3-py3.4.egg/click/core.py", line 610, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click-3.3-py3.4.egg/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click-3.3-py3.4.egg/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click-3.3-py3.4.egg/click/core.py", line 416, in invoke
    return callback(_args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/unp-0.2-py3.4.egg/unp.py", line 565, in cli
  File "/usr/local/lib/python3.4/dist-packages/unp-0.2-py3.4.egg/unp.py", line 210, in unpack
  File "/usr/local/lib/python3.4/dist-packages/unp-0.2-py3.4.egg/unp.py", line 243, in real_unpack
  File "/usr/local/lib/python3.4/dist-packages/unp-0.2-py3.4.egg/unp.py", line 71, in process
TypeError: can't use a string pattern on a bytes-like object

**Comment by abitrolly** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1701167

Hello @mitsuhiko. This package was packaged for Fedora. Do you have plans to support this project?
